name: Get Code Scanner Results

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Repo'
        default: 'WebGoat'
        required: true
jobs:
    
  # Job Name
  get-scanner-results:

    runs-on: ubuntu-latest

    steps:
      
      # Checkouts latest actions yaml file
      - uses: actions/checkout@v3
    
      # Get GHAS code scanner results
      - name: GHAS code scanner results
        id: ghasCodeScannerResults      
        uses: fjogeleit/http-request-action@v1.14.0
        with:
          url: "https://api.github.com/repos/sreepathivinod/WebGoat/code-scanning/analyses"
          timeout: 60000
          method: "GET"
          bearerToken: ${{ secrets.PAT_TOKEN }}

      - name: Show Analyses List Response
        run: |
          echo ${{ fromJson(steps.ghasCodeScannerResults.outputs.response).results[0].url }}
          echo ${{ steps.ghasCodeScannerResults.outputs.headers }}

