name: Get Code Scanner Results

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Repo'
        default: 'WebGoat'
        required: true
jobs:
    
  # Job Name
  get-scanner-results:

    runs-on: ubuntu-latest

    steps:
      
      # Checkouts latest actions yaml file
      - uses: actions/checkout@v3
    
      - name: Create Directory
        run: mkdir staging
        
      # Get GHAS code scanner results
      - name: GHAS code scanner results
        id: ghasCodeScannerResults      
        uses: fjogeleit/http-request-action@v1.14.0
        with:
          url: "https://api.github.com/repos/sreepathivinod/WebGoat/code-scanning/analyses"
          timeout: 60000
          method: "GET"
          bearerToken: ${{ secrets.PAT_TOKEN }}
          responseFile: staging/webgoat-results.json

      # List Scanner Results
      - name: Show Scanner Results Files
        run: |
          ls -lrt staging
          cat staging/webgoat-results.json
      
      - name: get properties
        id: json_properties
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: staging/webgoat-results.json

      - run: |
          echo ${{steps.json_properties.outputs.url}}
        


